// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"toko-api-fiber/internal/config"
	"toko-api-fiber/internal/delivery/http"
	"toko-api-fiber/internal/delivery/http/middleware"
	"toko-api-fiber/internal/repository"
	"toko-api-fiber/internal/usecase"
)

// Injectors from injector.go:

func InitializedApp() *config.App {
	viper := config.NewViper()
	app := config.NewFiber(viper)
	logger := config.NewLogrus(viper)
	db := config.NewGorm(viper, logger)
	validate := config.NewValidator(viper)
	productRepository := repository.NewProductRepository(db, logger)
	productUseCase := usecase.NewProductUseCase(db, logger, validate, productRepository)
	productController := http.NewProductController(productUseCase, logger)
	authMiddleware := middleware.NewAuthMiddleware(logger)
	configApp := config.NewApp(app, productController, authMiddleware, logger, validate, viper, db)
	return configApp
}

// injector.go:

var productSet = wire.NewSet(repository.NewProductRepository, usecase.NewProductUseCase, http.NewProductController)
