// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"toko-api-fiber/internal/config"
	"toko-api-fiber/internal/delivery/http"
	"toko-api-fiber/internal/delivery/http/middleware"
	"toko-api-fiber/internal/repository"
	"toko-api-fiber/internal/usecase"
	"toko-api-fiber/internal/util"
)

// Injectors from injector.go:

func InitializedApp() *config.App {
	viper := config.NewViper()
	logger := config.NewLogrus(viper)
	app := config.NewFiber(viper, logger)
	db := config.NewGorm(viper, logger)
	transaction := repository.NewTransaction(db)
	productRepository := repository.NewProductRepository(db, logger)
	productUsecase := usecase.NewProductUseCase(transaction, logger, productRepository)
	validate := config.NewValidator(viper)
	productController := http.NewProductController(productUsecase, logger, validate)
	userRepository := repository.NewUserRepository(db, logger)
	tokenUtil := util.NewTokenUtil(viper)
	userUsecase := usecase.NewUserUsecase(transaction, logger, userRepository, tokenUtil)
	userController := http.NewUserController(logger, userUsecase, validate)
	authMiddleware := middleware.NewAuthMiddleware(logger, tokenUtil, userUsecase)
	configApp := config.NewApp(app, productController, userController, authMiddleware, logger, validate, viper, db, tokenUtil)
	return configApp
}

// injector.go:

var productSet = wire.NewSet(repository.NewProductRepository, usecase.NewProductUseCase, http.NewProductController)

var userSet = wire.NewSet(repository.NewUserRepository, usecase.NewUserUsecase, http.NewUserController)
